services:
  backend:
    container_name: clockly-backend
    image: clockly-backend
    build: 
      context: ./backend
      dockerfile: Containerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
  # frontend:
  #   container_name: clockly-frontend
  #   image: clockly-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Containerfile
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - backend 
  #   environment:
  #     - BACKEND_URL=http://127.0.0.1:8000
  #     # - BACKEND_URL=http://192.168.1.45:8000
  #     - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.45
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   command:
  #     # npx expo start --tunnel # Exclusive (needed ngrok) 
  #     npx expo start -c --lan
  #   stdin_open: true 
  #   tty: true
  db: 
    container_name: clockly-db
    # hostname: clockly-db
    image: postgres
    env_file:
      - backend/.env
    environment:
      - POSTGRES_DB=database 
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  db-ui:
    container_name: pgadmin4
    image: docker.io/dpage/pgadmin4:9
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pg_admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pg_admin
      POSTGRES_HOST: db
      POSTGRES_DB: database
      POSTGRES_USER: database
      POSTGRES_PASSWORD: password
    ports:
      - 5050:80