services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  db: 
    container_name: clockly-db
    hostname: clockly-db
    image: docker.io/postgres
    env_file:
      - backend/.env
    environment:
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database 
    ports:
      - 5432:5432